### ISSUE TITLE
Undefined variable in src/js/api/profiles/update.js

### ISSUE THREAD

**Issue by Sindre1993** [NoroffFEU/social-media-client#33] opened 2022-11-07 09:46 UTC
Eslint returns an error in the updateProfileImage function.

```
C:\Users\Sindr\workflow-ca\social-media-client\src\js\api\profiles\update.js
  8:62  error  'id' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

**Comment by AnnaHelene01** [comment] 2022-11-07 13:53
Caught the same error in the updateProfileImage function:

/Users/annasaethre/Documents/GitHub/ca-workflow-2/src/js/api/profiles/update.js
  8:62  error  'id' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

**Comment by Fermain** [comment] 2022-11-08 08:06
Duplicate of #30

**Closed by Fermain** 2022-11-08 08:06 UTC
